class AppConst {
  static Map<String, String> supportLanMap = {
    "ZH-HANS": "简体",
    "ZH-HANT": "繁体",
    "EN-US": "英语",
    "SV": "瑞典",
    "JA": "日文",
    "PT-PT": "葡萄牙",
    "ES": "西班牙",
    "TR": "土耳其",
    "DE": "德文",
    "RU": "俄文",
    "FR": "法文",
    "IT": "意文",
    "PL": "波兰",
    "NL": "荷兰",
    "CS": "捷克",
    "SK": "斯洛伐克",
    "KO": "韩文",
    "DA": "丹麦文",
    "AR": "阿拉伯",
    "BG": "保加利亚",
    "EL": "希腊",
    "ET": "爱沙尼亚",
    "FI": "芬兰",
    "HU": "匈牙利",
    "ID": "印尼",
    "LT": "立陶宛",
    "LV": "拉脱维亚",
    "NB": "挪威",
    "RO": "罗马尼亚",
    "SL": "斯洛文尼亚",
    "UK": "乌克兰",
  };
  static List<String> allCountryLanguage = [
    "简体 ZH-HANS",
    "繁体 ZH-HANT",
    "英语 EN-US",
    "瑞典 SV",
    "日文 JA",
    "葡萄牙 PT-PT",
    "西班牙 ES",
    "土耳其 TR",
    "德文 DE",
    "俄文 RU",
    "法文 FR",
    "意文 IT",
    "波兰 PL",
    "荷兰 NL",
    "捷克 CS",
    "斯洛伐克 SK",
    "韩文 KO",
    "丹麦文 DA",
    "阿拉伯 AR",
    "保加利亚 BG",
    "希腊 EL",
    "爱沙尼亚 ET",
    "芬兰 FI",
    "匈牙利 HU",
    "印尼 ID",
    "立陶宛 LT",
    "拉脱维亚 LV",
    "挪威 NB",
    "罗马尼亚文 RO",
    "斯洛文尼亚 SL",
    "乌克兰 UK",
  ];
  static String deeplurl = 'https://api-free.deepl.com/v2/translate';
}
